name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Adjust to match your PHP version
          extensions: mbstring, bcmath
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-scripts --no-interaction --prefer-dist

      # Run Pint linting
      - name: Run Pint Lint
        run: composer lint
